# config.example.yml
server:
  port: 8080

providers:
  - provider: "openai"
    api_url: "http://127.0.0.1:9090/v1/chat/completions"
    api_key: "d2637479653f49009c79a7e224794df8"
    timeout: 60
    is_default: true
    models:
      - name: "random"
        weight: 10
        max_tokens: 2000
        temperature: 0.3

cache:
  enabled: true
  types: ["memory", "redis"]

  # 内存缓存特定配置
  memory:
    ttl:
      value: "permanent"          # 1小时 (支持: 30s, 5m, 2h, 1d, 1w, permanent)
    max_size: 100000000        # 最多存储1亿条记录

  # Redis缓存特定配置
  redis:
    host: "localhost"
    port: 6379
    password: ""
    db: 0
    ttl:
      value: "permanent"          # 7天 (也可以使用: permanent 表示永久存储)

prompt:
  template: "Translate the following text from %s to %s:\n\n%s"

openai:
  compatible_api:
    enabled: true                   # 是否启用 OpenAI 兼容接口
    path: "/v1"                     # API 路径前缀
    auth_tokens:                    # 允许的认证令牌列表
      - "tr-98584e33-f387-42cc-a467-f02513bd400d"



# config.example.yml 添加认证配置
transapi:
  tokens:
    - "tr-98584e33-f387-42cc-a467-f02513bd400d"

log:
  enabled: true
  file_path: "logs/translation.log"
  max_size: 100          # 单个文件最大大小，单位：MB
  max_age: 30            # 保留天数
  max_backups: 10        # 最大备份文件数
  queue_size: 1000       # 异步队列大小