name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build for multiple platforms
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build
        run: |
          mkdir -p dist
          VERSION=${GITHUB_REF#refs/tags/}
          NAME=transbridge
          OUTNAME=${NAME}-${VERSION}-${{ matrix.goos }}-${{ matrix.goarch }}
          
          if [ "${{ matrix.goos }}" = "windows" ]; then
            OUTNAME="$OUTNAME.exe"
          fi

          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/$OUTNAME .

      - name: Archive as .tar.gz
        run: |
          cd dist
          for f in *; do
            tar -czf "${f%.*}.tar.gz" "$f"
          done

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}